name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64, 386]
        include:
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm
            goarm: 6
          - goos: windows
            goarch: arm64
          - goos: linux
            goarch: arm64
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true

      - name: Build hugoArticleEncryptor
        run: |
          go build -v -o hugoArticleEncryptor -trimpath -ldflags "-s -w -buildid=" .

      - name: Rename Windows hugo encrypt
        if: matrix.goos == 'windows'
        run: |
          mv hugoArticleEncryptor hugoArticleEncryptor.exe

      - name: Change the name
        run: |
          mv hugoArticleEncryptor hugoArticleEncryptor-${{ env.ASSET_NAME }} || mv hugoArticleEncryptor.exe hugoArticleEncryptor-${{ env.ASSET_NAME }}.exe

      - name: Upload Releases
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: hugoArticleEncryptor-*
          draft: true
          prerelease: false
